### PR TITLE
Add option to skip copying

### PR DESCRIPTION
**Pull request by browniefed**
When using Next.js on Vercel the file system is locked after build phases.

So essentially I want to run the plugin in a copy phase during build time.
Then during a separate phase of building staticProps want to skip the copy and just replacement of the URLs which will still just be the same hash as was copied over.

If you feel like this is wrong or whatever I am happy to keep this as a separate fork and just use as is but figured I'd contribute back.

### CODE REVIEW

**Comment by sergioramos** [comment]
Thank you for the contribution 😉 

Couple of suggestions:

- rename `copy` to `dryRun` that defaults to `false`;
- add tests.

**Comment by browniefed** [comment]
Awesome, yeah as I was making the PR I was like "oh yeah it should probably be something like dry".

I'll toss some tests up tomorrow. Thanks.

**Comment by browniefed** [comment]
@sergioramos Added some tests. 

Outputs were committed in the repo prior. Essentially I clean the directories, test that they don't exist after a dry run but still do snapshots.

Then for the next set of tests it just tests that the directories were created.

**Comment by sergioramos** [comment]
merged https://github.com/sergioramos/remark-copy-linked-files/commit/2c45ad61224432e892e0eeeeedd8080abf9fda98

**Pull request closed without merging**
